### ISSUE TITLE
version record

### ISSUE THREAD

**Issue by jwcesign** [jwcesign/federation-metrics-adaptor#2]
```
@@ -45,14 +45,14 @@ require (
        k8s.io/kube-openapi v0.0.0-20230501164219-8b0f38b5fd1f
        k8s.io/kubectl v0.27.3
        k8s.io/metrics v0.27.3
        layeh.com/gopher-json v0.0.0-20201124131017-552bb3c4c3bf
        sigs.k8s.io/cluster-api v1.5.0-rc.0
        sigs.k8s.io/controller-runtime v0.15.0
-       sigs.k8s.io/custom-metrics-apiserver v1.25.1-0.20230308103314-bd3192a29bc8
+       sigs.k8s.io/custom-metrics-apiserver 等PR合入
        sigs.k8s.io/kind v0.17.0
        sigs.k8s.io/mcs-api v0.1.0
-       sigs.k8s.io/metrics-server v0.6.1-0.20230509102056-1a23b5bd2e12
+       sigs.k8s.io/metrics-server v0.6.1-0.20230706083104-796fc0f832c1
+        k8s.io/apiserver 等PR合入
        sigs.k8s.io/structured-merge-diff/v4 v4.2.3
        sigs.k8s.io/yaml v1.3.0
 )
```

**Comment by jwcesign** [comment]
```yaml
apiVersion: autoscaling.karmada.io/v1alpha1
kind: FederatedHPA
metadata:
  name: consumer-test
spec:
  minReplicas: 1
  maxReplicas: 1000
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: consumer-test
  behavior: # 这里是重点
    scaleDown:
      stabilizationWindowSeconds: 300 # 需要缩容时，先观察 5 分钟，如果一直持续需要缩容才执行缩容
    scaleUp:
      stabilizationWindowSeconds: 0 # 需要扩容时，立即扩容
```
